import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "./globals.css";
import { SkeletonTheme } from 'react-loading-skeleton';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SkeletonTheme baseColor="#E0E0E0" highlightColor="#525252" duration={3}>
          <div className="container">
            <Toaster position="top-right" />
            {children}
          </div>
        </SkeletonTheme>
      </body>
    </html>
  );
}
