import { AuthProvider } from "@/context/AuthProvider";
import { FollowingProvider } from "@/context/FollowingProvider";
import { Geist, Geist_Mono, Inter, Montserrat, Poppins } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins", subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

const monteserrat = Montserrat({
  variable: "--font-monteserrat", subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

const inter = Inter({
  variable: "--font-inter", subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${monteserrat.variable} ${inter.variable}`}>
        <AuthProvider>
          <FollowingProvider>
            <div className="appContainer">
              <Toaster position="top-right" />
              {children}
            </div>
          </FollowingProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
