import Navbar from "@/components/Navbar";
import TitleBar from "@/components/TitleBar";
import { Geist, Geist_Mono, Poppins, Montserrat } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

const monteserrat = Montserrat({
  variable: "--font-monteserrat",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${monteserrat.variable}`}>
        <div className="container">
          <TitleBar />
          <div className="chatContainer">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
