import { Geist, Geist_Mono, Oswald, Roboto, Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";
import ProductsProvider from "@/context/ProductsContext";
import CartProvider from "@/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
})

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
})

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} ${roboto.variable} ${montserrat.variable}`}>
        <div className="container">
          <ProductsProvider>
            <CartProvider>
              {
                <>
                <NavBar />
                {children}
                </>
              }
            </CartProvider>
          </ProductsProvider>
        </div>
      </body>
    </html>
  );
}